### ISSUE TITLE
Update Elixir/Erlang/Node versions

### ISSUE THREAD

**Issue by kkrug** [GSA/Challenge_gov#1335]
## User Story

As a developer, I want to update Elixir, Erlang, and Node so that they are on the latest versions.

## Acceptance Criteria

1. Given the versions are updated, when interacting with the application, then the functionality should be unchanged.
2. Given the versions are successfully updated, then the documentation should reflect those changes..

## Tasks:
- [ ] Update Elixir to 1.16
- [ ] Update Erlang to 26
- [ ] Update Node to 20 LTS
- [ ] Update documentation

## Background

[Any helpful contextual notes or links to artifacts/evidence, if needed]
