### ISSUE TITLE
Check CircleCI configuration to sync with current node version

### ISSUE THREAD

**Issue by kkrug** [GSA/Challenge_gov#1336]
## User Story

As a developer, I want to check the CircleCI configuration so that it syncs with the current version of node for testing.

## Acceptance Criteria

1. Given the node version is updated, when CircleCI configuration is checked then it should sync with the current node version.

## Tasks:
- [ ] Check CircleCI configuration to sync with current node version
- [ ] Make CircleCI configuration changes, if necessary.
- [ ] Update documentation, if necessary.

## Background

This issue is only relevant after the node version is updated per issue #1335.
