### ISSUE TITLE
QA Checklist #2

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1348]
As a Challenge.gov product team, in order to ensure the product features and updates we develop are secure, high quality and usable, we would like to establish a checklist of requirements we will follow as part of recuring tasks.

This is a continuation of #1321 

Acceptance criteria:

- [x]  Task-specific QA checklists are established
- [x]  QA checklists are added to appropriate backlog item templates
- [x]  Conduct QA steps to verify the recent PR #1340 

Resources:

1. Previous QA checklist: https://docs.google.com/document/d/1j0yEmaLPu_5c4jev9UGH4lGsYxsbfNv1R5J0crJQWGc/edit#heading=h.dje2h2c1dylr
2. Admin test procedures (CMP tables): https://docs.google.com/spreadsheets/d/1ocFFLkQl1wTVgD1BJwG1nifoNA_mOlqcCODkW8k6vCA/edit#gid=828822100

**Comment by jdonis** [comment]
PR with QA template
https://github.com/GSA/Challenge_gov/pull/1357
