### ISSUE TITLE
Challenge Portal Header

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1362]
Note: This work needs to be deployed to [challenge portal eval dev environment](https://challenge-portal-eval-dev.app.cloud.gov/) ([challenge_gov repo > eval main branch](https://github.com/GSA/Challenge_gov/tree/eval-main))

### User Story
As a site user with challenge manager or public solver roles, in order to build my trust using challenge.gov site, I would like to see consistent branding and styling from any page of the site.

**Acceptance criteria:**

- [x] Challenge.gov header and main nav are displayed for logged-in users using challenge management and submissions portal
- [x] When the user is logged-in, Logout button is displayed (instead of Login)
  - [x]  https://github.com/GSA/Challenge_platform/issues/24

**Tasks:**

- [ ] Dev task 1
- [ ] Dev task 2

### Definition of Done

**Doing (dev team)**
- [x] Code complete 
- [x] Code is organized appropriately
- [x] Any known trade offs are documented in the associated GH issue
- [x] Code is documented, modules, shared functions, etc.
~- [ ] Automated testing has been added or updated in response to changes in this PR~
- [x] The feature is smoke tested to confirm it meets requirements
~- [ ] Database changes have been peer reviewed for index changes and performance bottlenecks~
- [x] PR that changes or adds UI
  - [x] include a screenshot of the WAVE report for the altered pages
  - [x] Confirm changes were validated for mobile responsiveness
- [x] PR approved / Peer reviewed 
- [x] Security scans passed
~- [ ] Automate accessibility tests passed~
- [x] Build process and deployment is automated and repeatable
~- [ ] Feature toggles if appropriate~
- [x] Deploy to staging
- [x] Move card to testing column in the board
---
**Staging**
- [x] Accessibility tested (Marni)
  - [ ]  Keyboard navigation
  - [ ]  Focus confirmed
  - [ ] Color contrast compliance
  - [ ] Screen reader testing 
- [x] Usability testing: mobile and desktop (Tracy or Marni)
- [ ] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [ ] Windows/Chrome
  - [ ] Windows/Edge
  - [ ] Mac/Chrome
  - [ ] Mac/Safari
  - [ ] iOS/Safari
- [x] AC review (Renata)
- [ ] ~Deploy to production (production-like environment for eval capability) (dev team)~
- [x] Move to production column in the board
---
**Production**
- [ ] ~User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team)~ 
- [x] PO / PM approved (Jarah or Renata)
- [x] AC is met and it works as expected (Jarah or Renata)
- [x] Move to done column in the board (Jarah or Renata)

**Comment by r-bartlett-gsa** [comment]
Figma link: https://www.figma.com/design/VfdBFG8ShVnOStdSNYy9fR/Challenge.Gov-Component-Library?node-id=783-40675&t=63ttnQ9V6X1V72A5-0



![Image](https://github.com/user-attachments/assets/59477b5c-906c-4c17-bff8-4561bb9be09a)



![Image](https://github.com/user-attachments/assets/eca16819-80dc-43e6-ab06-75a42115e600)

**Comment by r-bartlett-gsa** [comment]
Work progress document: https://docs.google.com/document/d/11blju-lsqhzP4RlJ5f7vkR39q1eXFjnybFXkVeb-JjE/edit?usp=sharing

**Comment by jairoanaya** [comment]
**Trade off:** the original header nav was removed to open place holder for utility menu

**WAVE Report**

Wave report logged out

![Image](https://github.com/user-attachments/assets/fc0e3d9d-f90a-4c85-97aa-376a5c298d81)

Wave report Logged In
![Image](https://github.com/user-attachments/assets/57a4ebd9-a5ee-47f7-a409-edc71eeaa297)

**Evidences**

Header Gov Notice Logged out
![Image](https://github.com/user-attachments/assets/63cc9c10-f909-4c14-86f9-ca28204be510)

Header Gov Notice Logged out - responsive
![Image](https://github.com/user-attachments/assets/47e782f3-8e3d-483e-af33-cba353125ac2)

Header Gov Notice Collapsed Logged out - responsive
![Image](https://github.com/user-attachments/assets/43225f7f-3405-4345-a6e8-351accd2f8b5)

Header menu responsive - logged out
![Image](https://github.com/user-attachments/assets/8da5cc87-e347-4156-af2b-951f28d58f72)

Header Gov Notice Logged In responsive
![Image](https://github.com/user-attachments/assets/79f8c607-e8ca-439a-8335-6505bf2263ba)

Header Menu Responsive Logged In
![Image](https://github.com/user-attachments/assets/d92b297f-4031-4cff-a57d-cf718b657b7f)

Header Gov Notice Expanded Logged In 
![Image](https://github.com/user-attachments/assets/f9ec7183-3932-425b-a017-edf2d65169f3)

Header Gov Notice Collapse Logged In 
![Image](https://github.com/user-attachments/assets/0100d035-faf4-431d-8aba-b1df93e58264)

**Comment by jairoanaya** [comment]
Work done:

- Code understanding from challenge_platform and challenges & prizes
- Code was adapted from challenge_platform and challenges & prizes
- Team feedback document created on Google - https://docs.google.com/document/d/11blju-lsqhzP4RlJ5f7vkR39q1eXFjnybFXkVeb-JjE/edit?usp=drive_link
- Team feedback received for implementation
- CSS update
- Testing in Desktop and Responsive
- Deploying into staging
- Feature ready for testing on staging
- Branch recreation from eval - new instruction
- Testing in Desktop and Responsive locally
- Feature ready for testing on eval-main staging - https://challenge-portal-eval-dev.app.cloud.gov/

Notes:

Due to a new branching instruction - a new branch was recreated from eval-main in order to deploy the feature into Eval version. Previous branches were deleted or archived.

**Comment by r-bartlett-gsa** [comment]
@jairoanaya Same request as in other user stories, please check the Definition of Done list.
Also, please update the header background to white, instead of grey.
Also also, after opening and closing the menu on mobile, there's empty space on the right hand side, the page size does not reset correctly: https://app.screencast.com/TGHNkgaMzHbTq

**Comment by jairoanaya** [comment]
@r-bartlett-gsa definition of done addressed. 

Regarding changing the background could you confirm it should look like the following screenshot:

![Image](https://github.com/user-attachments/assets/1f84f998-8852-4b5b-83e5-8191b201c3f1)

I confirm I replicated the unexpected responsive behavior. Reviewing the issue in detail. Expect to provide additional inputs.

**Comment by r-bartlett-gsa** [comment]
Thank you @jairoanaya! I confirm the background color in your comment above.

**Comment by jairoanaya** [comment]
> [@jairoanaya](https://github.com/jairoanaya) Same request as in other user stories, please check the Definition of Done list. Also, please update the header background to white, instead of grey. Also also, after opening and closing the menu on mobile, there's empty space on the right hand side, the page size does not reset correctly: https://app.screencast.com/TGHNkgaMzHbTq

@r-bartlett-gsa after reviewing this issue I found the following: 

The reported problem occurs because an internal element is not responsive as shown in the following picture. 
![Image](https://github.com/user-attachments/assets/96cf6772-de8d-415f-8ef2-77b9a01ccb70)

This issue is expected to be resolved (by itself) by implementing #1388. I suggest waiting for the implementation of the 'Manager's dashboard.' Do you agree?

**Comment by r-bartlett-gsa** [comment]
@jairoanaya Sounds like a plan. Let's wait until #1388 is completed and reassess then. Thank you!

**Comment by jairoanaya** [comment]
@r-bartlett-gsa I confirm the background color has been changed (on the logged in state), please review if the changes satisfy the acceptance criteria.

**Comment by TCKapGrp** [comment]
Hi @jairoanaya and @r-bartlett-gsa , in the screenshots from wireframes  as well as the mobile responsive view, the logout button is white.  On the desktop view, the button is blue.  I'm pinging @mhotch24  for responsive and a11y testing.

**Comment by r-bartlett-gsa** [comment]
@jairoanaya and @TCKapGrp No changes to button colors and styles are needed at this time. The consistency of button colors and styles across all apps will be addressed as part of fit & finish updates at a later time.

**Comment by mhotch24** [comment]
@r-bartlett-gsa

**Usability Findings:**
- Still seeing inconsistencies between the headers of Rails and Portal-dev; header bg color, body bg color, logo sizing, switch task button.

**Feature Accessibility Findings:**
- Some issues with labelling/voice over. Inconsistencies with how items are Rails are named so it's not a consistent experience:
- Examples: 'Find a Challenge' voices 'Active Challenges'. It needs to say 'Find a Challenge'.

**Comment by r-bartlett-gsa** [comment]
@jairoanaya Please address the following accessibility issue by updating header nav button aria labels so they match the actual label text:

> Some issues with labelling/voice over:
> Examples: 'Find a Challenge' voices 'Active Challenges'. It needs to say 'Find a Challenge'.

**Comment by jairoanaya** [comment]
@mhotch24 

Context: for this feature I combined the header from Challenge.gov and eval platform. I have the following questions:

Switch Task does not have any function, still implementing the button?
All arias and labels should follow eval platform?

@r-bartlett-gsa changing the color for logout button requires a minimum effort and can be done on this usability feedback, should I include it now or wait for fit & finish?

**Comment by r-bartlett-gsa** [comment]
@jairoanaya Please do not implement Switch Task button and do not update the current Logout button at this time. These items will be updated at a later time, consistently across all apps.

Please update aria labels so they meet A11y requirements (even if it does not match/follow eval)

**Comment by jairoanaya** [comment]
@r-bartlett-gsa @mhotch24 the following feedback has been implemented and deployed to https://challenge-portal-eval-dev.app.cloud.gov/

- header bg color to white.
- body bg color to white
- logo sizing as is eval platfrom
- switch task button not implemented.
- labelling/voice over have resolved and have the same behavior than eval platform.
