### ISSUE TITLE
Axe Report Review

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1439]
- [x] **The following tasks are timeboxed at 4 hours:**
  - [x] Review axe report for challenge_gov repo, #1405 
  - [x] Review axe report for challenges-and-prizes repo, https://github.com/GSA/challenges-and-prizes/issues/2013
  - [x] Review axe report for citizenscience repo, https://github.com/GSA/citizenscience.gov/issues/426
- [x] Meet with gov PM to discuss findings and prioritization

**Comment by r-bartlett-gsa** [comment]
@TCKapGrp / @mhotch24 Please timebox axe reports reviews for both repos at 4 hours, and then meet to discuss your approach / findings / recommendations.

**Comment by mhotch24** [comment]
@r-bartlett-gsa Here are two documents which outline the axe reporting, findings, and recommendations.
[Challenge and Prizes](https://docs.google.com/document/d/19CA_jlKCcTX9rEbgGSzjY3h8UEyGLU7T3ighHLkmKVw/edit)
[Challenge_gov (Public Solver Portal)](https://docs.google.com/document/d/1qnHoMIqbpJUuN0GwWystUEfhvsnbFgPPE6e4Pn2GKV0/edit#heading=h.818yzyhrixz9)

Meeting schedule to review on 10/23/24

**Comment by mhotch24** [comment]
@r-bartlett-gsa Adding CitizenScience report here: https://docs.google.com/document/d/1NGRXbStkcMoK5DXZq4kiNbXoeg-7uHmCCJ6y5BmqTRA/edit?usp=sharing
