### ISSUE TITLE
Update external traffic calls to use the egress proxy

### ISSUE THREAD

**Issue by danivovich** [GSA/Challenge_gov#1445]
## Context

The egress proxy is configured in the eval dev space. This work should then be set to merge to `eval-main`.

Finch is not working with the double proxy hop setup we ended up needing, but HTTPoison is working.

## Tasks

- [x] Replace Finch calls with HTTPoison calls
- [x] Update tests that rely on Finch
- [x] Configure HTTPoison to use the egress proxy when configured (so that its not used locally or in test)
- [x] Remove Finch and any other HTTP library that isn't HTTPoison or a dependency of HTTPoison

## Technical Detail

```elixir
# If System.get_env("LOCAL_PROXY_HOST") is set, add options to the HTTPoison get calls that look like this:
options = [proxy: {System.get_env("LOCAL_PROXY_HOST"), 8888}] 
HTTPoison.get("https://www.google.com", [], options)
```

This is likely feasible to do in a module where `use HTTPoison.Base` is invoked, and then implementing the callback `process_request_options` so that these options are added to every call from that module.

### Example Usage
Here is an example of the responses expected when the proxy allows vs denies traffic, so that you can get your pattern matches (although we probably handle `{:error ...}` the same way most of the time.
```
iex(19)> HTTPoison.get("https://yahoo.com", [], options)                                                                                                                                                                         
{:error, %HTTPoison.Error{reason: :proxy_error, id: nil}}                                                                      
iex(20)> HTTPoison.get("https://www.google.com", [], options)                                                                  
{:ok,                                                                                                                          
 %HTTPoison.Response{ ....
```

## Deployment Target

This work must be based on `eval-main` and merge back to `eval-main`

**Comment by r-bartlett-gsa** [comment]
Related Egress work:
#1437
https://github.com/GSA/Challenge_platform/issues/31

**Comment by afeijoo** [comment]
Archiving repo; no longer applicable.
