### ISSUE TITLE
SPIKE: Challenges Meta Data Updates

### ISSUE THREAD

**Issue by r-bartlett-gsa** [GSA/Challenge_gov#1493]
Investigate a long term solution for improving how challenge pages are rendered and how that influences meta data for these pages, as well as URLs structure.

---
### User Story
As a site user, in order to find relevant Challenge.gov pages and navigate the site content effectively, I would like the page titles and descriptions to accurately reflect the page content.

**Acceptance Criteria:**

- [ ] The following changes are applies to page titles, og:titles, meta descriptions and og:descriptions
- [ ] Challenges:
  - [ ] Title: [challenge title] | Challenge.gov
    - [ ] [challenge title] is provided by challenge managers via challenge creation wizard
  - [ ] Description: [challenge tagline] 
    - [ ] [challenge tagline] is provided by challenge managers via challenge creation wizard

### Definition of Done

**Doing (dev team)**
- [ ] Code complete 
- [ ] Code is organized appropriately
- [ ] Any known trade offs are documented in the associated GH issue
- [ ] Code is documented, modules, shared functions, etc.
- [ ] Automated testing has been added or updated in response to changes in this PR
- [ ] The feature is smoke tested to confirm it meets requirements
- [ ] Database changes have been peer reviewed for index changes and performance bottlenecks
- [ ] PR that changes or adds UI
  - [ ] include a screenshot of the WAVE report for the altered pages
  - [ ] Confirm changes were validated for mobile responsiveness
- [ ] PR approved / Peer reviewed 
- [ ] Security scans passed
- [ ] Automate accessibility tests passed
- [ ] Build process and deployment is automated and repeatable
- [ ] Feature toggles if appropriate
- [ ] Deploy to staging
- [ ] Move card to testing column in the board
---
**Staging**
- [ ] Accessibility tested (Marni)
  - [ ]  Keyboard navigation
  - [ ]  Focus confirmed
  - [ ] Color contrast compliance
  - [ ] Screen reader testing 
- [ ] Usability testing: mobile and desktop (Tracy or Marni)
- [ ] Cross browser testing - UI rendering is performant on below listed devices/browsers (Tracy or Marni)
  - [ ] Windows/Chrome
  - [ ] Windows/Edge
  - [ ] Mac/Chrome
  - [ ] Mac/Safari
  - [ ] iOS/Safari
- [ ] AC review (Renata)
- [ ] Deploy to production (production-like environment for eval capability) (dev team)
- [ ] Move to production column in the board
---
**Production**
- [ ] User and security documentation has been reviewed for necessary updates (Renata/Tracy/Dev team) 
- [ ] PO / PM approved (Jarah or Renata)
- [ ] AC is met and it works as expected (Jarah or Renata)
- [ ] Move to done column in the board (Jarah or Renata)

**Comment by jairoanaya** [comment]
@r-bartlett-gsa Does the AC require that metadata and title be displayed only at the browser level for informational purposes (to help the user, as mentioned), or for SEO purposes aswell?

**Comment by r-bartlett-gsa** [comment]
> [@r-bartlett-gsa](https://github.com/r-bartlett-gsa) Does the AC require that metadata and title be displayed only at the browser level for informational purposes (to help the user, as mentioned), or for SEO purposes aswell?

@jairoanaya The metadata needs to be part of the page source code.

**Comment by jairoanaya** [comment]
@r-bartlett-gsa please refer to the following documents to find the best strategy to fix this issue: https://docs.google.com/document/d/171ui2XhSyDaaQVF-rfR9PqZfH-SBHKmqW4bidek7kd0/edit?tab=t.0

Additionally, follow these previous documents:

https://docs.google.com/document/d/102LYIxCKyHV9mzCpUan4yGrFPKTQ8ybbvZ2uiFWdJfQ/edit?usp=sharing
https://docs.google.com/document/d/1898Ws9BT7aoFe6aBOm-LaTA_z18DRwdP/edit?usp=sharing&ouid=113629486303827540217&rtpof=true&sd=true
https://docs.google.com/document/d/1Jg9MQ0BUCnK7LDl7gqoId6hUUIyvdpxC/edit?usp=sharing&ouid=113629486303827540217&rtpof=true&sd=true

**Comment by afomi** [comment]
render the pages using phoenix and pass description data as meta tags

**Comment by afeijoo** [comment]
Archiving repo; no longer applicable.
